name: cara_ou_coroa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/btn_voltar.png
    - assets/btn_jogar.png
    - assets/cara.png
    - assets/coroa.png
    - assets/logo.png

